name: Deploy to Amazon EC2

on:
  push:
    branches:
      - develop # 최종 배포 시 main으로 변경할 것

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: thinkerbell-cicd-s3-bucket
  CODE_DEPLOY_APPLICATION_NAME: thinkerbell-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: thinkerbell-codedeploy-group

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    # (1) 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
      
    # (2) gradlew에 실행 권한 부여
    - name: Make gradlew executable
      run: chmod +x gradlew

    # (3) JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    # (4) YML 파일 생성
    - name: Set YML, Config, Key
      run: |
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          echo "${{ secrets.FIREBASE_CONFIG }}" | base64 --decode > src/main/java/depth/mvp/thinkerbell/global/config/FirebaseConfig.java
          echo "${{ secrets.FIREBASE_KEY }}" | base64 --decode > src/main/resources/neverland-thinkerbell-firebase-adminsdk-n4ik2-49baee872c.json
          ls -l src/main/resources
          ls -l src/main/java/depth/mvp/thinkerbell/global/config

    # (5) Gradle build (Test 제외)
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: clean build -x test

    # (6) AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: ${{ env.AWS_REGION }}

    # (7) 빌드 결과물을 S3 버킷에 업로드
    - name: Upload to AWS S3
      run: |
        aws deploy push \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --ignore-hidden-files \
          --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
          --source .

    # (8) S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
    - name: Deploy to AWS EC2 from S3
      run: |
        aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
